package com.wutsi.platform.tenant.entity

enum class ToggleName {
    ACCOUNT,
    ACCOUNT_BANK,
    ACCOUNT_MOBILE_MONEY,
    CART,
    CONTACT,
    ORDER,
    ORDER_PAYMENT,
    PAYMENT,
    SCAN,
    SEND,
    SHIPPING,
    SHIPPING_LOCAL_PICKUP,
    SHIPPING_LOCAL_DELIVERY,
    SHIPPING_INTERNATIONAL_DELIVERY,
    STORE,
    STORE_DIGITAL_PRODUCT,
    SWITCH_ENVIRONMENT,
}
