server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    com.wutsi.platform.tenant: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"

wutsi:
  client-id: wutsi-tenant
  application:
    name: wutsi-tenant
    asset-url: http://localhost:${server.port}/static
  platform:
    security:
      type: jwt
    tracing:
      client-id: ${wutsi.application.name}
      device-id-provider:
        type: header

  tenants:
    - id: 1
      name: Wutsi
      domain-name: www.wutsi.com
      currency: XAF
      countries:
        - CA
        - CM
        - DE
        - FR
        - GB
        - US
      languages:
        - en
        - fr
      logos:
        - type: PICTORIAL
          url: "${wutsi.application.asset-url}/tenants/1/logos/pictorial.png"
        - type: WORDMARK
          url: "${wutsi.application.asset-url}/tenants/1/logos/wordmark.png"
