server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    com.wutsi.platform.tenant: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"

wutsi:
  client-id: wutsi-tenant
  application:
    name: wutsi-tenant
    asset-url: http://localhost:${server.port}
    asset-root-url: ${wutsi.application.asset-url}/static/wutsi-tenant-server
  platform:
    security:
      type: jwt
    tracing:
      client-id: ${wutsi.application.name}
      device-id-provider:
        type: header

  tenants:
    - id: 1
      name: Wutsi
      domain-name: www.wutsi.com
      support-email: herve.tchepannou@wutsi.com
      install-url: https://www.wutsi.app
      currency: XAF
      currencySymbol: FCFA
      number-format: "#,###,##0"
      monetary-format: "#,###,##0 FCFA"
      date-format: "dd MMM yyy"
      time-format: "HH:mm"
      date-time-format: "dd MMM yyy, HH:mm"
      logos:
        - type: PICTORIAL
          url: "${wutsi.application.asset-root-url}/tenants/1/logos/pictorial.png"
        - type: WORDMARK
          url: "${wutsi.application.asset-root-url}/tenants/1/logos/wordmark.png"
      countries:
        - CM
        - GB
        - CA
      languages:
        - en
        - fr
      mobile-carriers:
        - mtn
        - orange
      limits:
        min-cashin: 500
        min-cashout: 500
      fees:
        - transaction-type: transfer  # 100 FCFA fees on transfer over 5,000 FCFA, fees paid by sender
          apply-to-sender: true
          threshold: 5000
          percent: 0
          amount: 100
        - transaction-type: transfer  # No fees when retailer transfers $$ to customer for cashin
          apply-to-sender: false
          from-retail: true
          percent: 0
          amount: 0
        - transaction-type: transfer  # 2% fees when customer transfers $$ to retail for cashout
          apply-to-sender: true
          to-retail: true
          percent: 0.02
          amount: 0
        - transaction-type: cashout   # 1% on cashout, fees paid by sender
          apply-to-sender: true
          percent: 0.01
          amount: 0
        - transaction-type: payment   # 5% on cashout, fees paid by receiver (merchant)
          apply-to-sender: false
          percent: 0.04
          amount: 0

  mobile-carriers:
    - code: mtn
      name: MTN
      countries:
        - CM
      phone-prefixes:
        CM:
          - "+23767"
          - "+237650"
          - "+237651"
          - "+237652"
          - "+237653"
          - "+237654"
          - "+237675"
          - "+237676"
          - "+237677"
          - "+237678"
          - "+237679"
          - "+237680"
      logos:
        - type: PICTORIAL
          url: "${wutsi.application.asset-root-url}/mobile-carriers/mtn/logos/pictorial.png"
        - type: WORDMARK
          url: "${wutsi.application.asset-root-url}/mobile-carriers/mtn/logos/wordmark.png"

    - code: orange
      name: Orange
      countries:
        - CM
        - GB
        - CA
      phone-prefixes:
        CM:
          - "+23769"
          - "+237655"
          - "+237656"
          - "+237657"
          - "+237658"
          - "+237659"
        GB:
          - "+44"
        CA:
          - "+1"
      logos:
        - type: PICTORIAL
          url: "${wutsi.application.asset-root-url}/mobile-carriers/orange/logos/pictorial.png"
        - type: WORDMARK
          url: "${wutsi.application.asset-root-url}/mobile-carriers/orange/logos/wordmark.png"
