server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    com.wutsi.platform.tenant: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"

wutsi:
  client-id: wutsi-tenant
  application:
    name: wutsi-tenant
    asset-url: http://localhost:${server.port}
    asset-root-url: ${wutsi.application.asset-url}/static/wutsi-tenant-server
  platform:
    security:
      type: jwt
    stream:
      name: ${wutsi.application.name}
      type: local
    tracing:
      client-id: ${wutsi.application.name}
      device-id-provider:
        type: header

  toggles:
    - name: ACCOUNT
      enabled: true
      description: Enable accounts management

    - name: ACCOUNT_BANK
      enabled: false
      description: Enable support for bank accounts

    - name: ACCOUNT_MOBILE_MONEY
      enabled: true
      description: Enable support for mobile money

    - name: CASHIN
      enabled: true
      description: Enable cash-in

    - name: CASHOUT
      enabled: true
      description: Enable cash-out

    - name: CART
      enabled: true
      description: Enable shopping cart

    - name: CONTACT
      enabled: true
      description: Enable the contact module

    - name: ORDER
      enabled: true
      description: Enable Order Management

    - name: ORDER_PAYMENT
      enabled: true
      description: Enable Payments on Orders

    - name: PAYMENT
      enabled: false
      description: Enable Payment Module

    - name: SCAN
      enabled: true
      description: Enable QR Code Scanning Module

    - name: SEND
      enabled: true
      description: Enable Money Transfer Module

    - name: SHIPPING
      enabled: true
      description: Enable Shipping Module

    - name: SHIPPING_IN_STORE_PICKUP
      enabled: true
      description: Enable in-store pickup shipping

    - name: SHIPPING_LOCAL_PICKUP
      enabled: false
      description: Enable Local pickup shipping

    - name: SHIPPING_LOCAL_DELIVERY
      enabled: true
      description: Enable deliveries in the same city

    - name: SHIPPING_INTERNATIONAL_DELIVERY
      enabled: false
      description: Enable support for international shipping

    - name: SHIPPING_EMAIL_DELIVERY
      enabled: true
      description: Enable support for email delivery
      environments: [ 'test' ]

    - name: STORE
      enabled: true
      description: Enable Store Module

    - name: STORE_DIGITAL_PRODUCT
      enabled: true
      description: Enable support for digital product
      environments: [ 'test' ]

    - name: TRANSACTION_HISTORY
      enabled: true
      description: Display transaction history?

    - name: SWITCH_ENVIRONMENT
      enabled: true
      description: Enable the ability to switch from PROD to TEST environment

  tenants:
    - id: 1
      name: Wutsi
      domain-name: www.wutsi.com
      support-email: support@wutsi.app
      install-url: https://www.wutsi.app
      install-android-url: https://play.google.com/store/apps/details?id=com.wutsi.wutsi_wallet
      #install-ios-url:
      webapp-url: https://wutsi-web-test.herokuapp.com
      currency: XAF
      currencySymbol: FCFA
      number-format: "#,###,##0"
      monetary-format: "#,###,##0 FCFA"
      date-format: "dd MMM yyy"
      time-format: "HH:mm"
      date-time-format: "dd MMM yyy, HH:mm"
      logos:
        - type: PICTORIAL
          url: "${wutsi.application.asset-root-url}/tenants/1/logos/pictorial-round.png"
        - type: WORDMARK
          url: "${wutsi.application.asset-root-url}/tenants/1/logos/wordmark.png"
      countries:
        - CM
        - GB
        - CA
      languages:
        - en
        - fr
      mobile-carriers:
        - mtn
        - orange
      limits:
        min-cashin: 500
        min-cashout: 500
      fees:
        - transaction-type: CHARGE  # 10% fees on charges - applied to merchant
          percent: 0.10
          applyToSender: false
        - transaction-type: CASHIN  # No fees on cashin with mobile money - applied to sender
          payment-method-type: MOBILE
          percent: 0.0
          applyToSender: true
        - transaction-type: CASHOUT  # 2.0% fees on cashout with mobile money - applied to sender
          payment-method-type: MOBILE
          percent: 0.020
          applyToSender: true

      product:
        default-picture-url: "${wutsi.application.asset-root-url}/products/nopicture.png"
      test-user-ids:
        - 16   # Herve
        - 18   # Eric - phone #2
        - 29   # Eric - phone #1
        - 19   # Louis
        - 23   # Mathis
        - 39   # Maison H
        - 47   # MTN Retail Account #1
        - 86   # Nadine
      test-phone-numbers:
        - "+237670000001"   # MTN Test Account #1
        - "+237670000002"   # MTN Test Account #2
        - "+237670000011"   # MTN Retail Account #1
        - "+237690000001"   # OM Test Account #1 - Maison H (business account)
        - "+237690000002"   # OM Test Account #2

  mobile-carriers:
    - code: mtn
      name: MTN
      countries:
        - CM
      phone-prefixes:
        CM:
          - "+23767"
          - "+237650"
          - "+237651"
          - "+237652"
          - "+237653"
          - "+237654"
          - "+237675"
          - "+237676"
          - "+237677"
          - "+237678"
          - "+237679"
          - "+237680"
          - "+237681"
      logos:
        - type: PICTORIAL
          url: "${wutsi.application.asset-root-url}/mobile-carriers/mtn/logos/pictorial.png"
        - type: WORDMARK
          url: "${wutsi.application.asset-root-url}/mobile-carriers/mtn/logos/wordmark.png"

    - code: orange
      name: Orange
      countries:
        - CM
        - GB
        - CA
      phone-prefixes:
        CM:
          - "+23769"
          - "+237655"
          - "+237656"
          - "+237657"
          - "+237658"
          - "+237659"
        GB:
          - "+44"
        CA:
          - "+1"
      logos:
        - type: PICTORIAL
          url: "${wutsi.application.asset-root-url}/mobile-carriers/orange/logos/pictorial.png"
        - type: WORDMARK
          url: "${wutsi.application.asset-root-url}/mobile-carriers/orange/logos/wordmark.png"
