wutsi:
  client-id: wutsi-tenant
  application:
    asset-url: https://prod-wutsi.s3.amazonaws.com
  platform:
    security:
      type: jwt
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}


  tenants:
    - id: 1
      name: Wutsi
      domain-name: www.wutsi.com
      support-email: support@wutsi.app
      install-url: https://www.wutsi.app
      install-android-url: https://play.google.com/store/apps/details?id=com.wutsi.wutsi_wallet
      #install-ios-url:
      webapp-url: https://www.wutsi.me
      currency: XAF
      currencySymbol: FCFA
      number-format: "#,###,##0"
      monetary-format: "#,###,##0 FCFA"
      date-format: "dd MMM yyy"
      time-format: "HH:mm"
      date-time-format: "dd MMM yyy, HH:mm"
      logos:
        - type: PICTORIAL
          url: "${wutsi.application.asset-root-url}/tenants/1/logos/pictorial-round.png"
        - type: WORDMARK
          url: "${wutsi.application.asset-root-url}/tenants/1/logos/wordmark.png"
      countries:
        - CM
      languages:
        - en
        - fr
      mobile-carriers:
        - mtn
        - orange
      limits:
        min-cashin: 500
        min-cashout: 5000
      fees:
        - transaction-type: CHARGE  # 10% fees on charges - applied to merchant
          percent: 0.10
          applyToSender: false
        - transaction-type: CASHIN  # 2.5% fees on cashin with mobile money - applied to sender
          payment-method-type: MOBILE_MONEY
          percent: 0.025
          applyToSender: true
        - transaction-type: CASHOUT  # 2.0% fees on cashout with mobile money - applied to sender
          payment-method-type: MOBILE_MONEY
          percent: 0.020
          applyToSender: true
      product:
        default-picture-url: "${wutsi.application.asset-root-url}/products/nopicture.png"
      test-user-ids:
        - 1  # Herve
        - 2  # Louis
        - 5  # Patrick
        - 7  # Eric
        - 52 # Nadine
