wutsi:
  client-id: wutsi-tenant
  application:
    asset-url: https://int-wutsi.s3.amazonaws.com
  platform:
    security:
      type: jwt
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
