openapi: "3.0.0"
info:
  title: "Wutsi Tenant API"
  description: |
    API that provide information about tennants
  version: "1.0.0"

servers:
  - url: https://wutsi-tenant-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-tenant-server-prod.herokuapp.com
    description: Production

paths:
  /v1/tenants/{id}:
    get:
      operationId: "get-tenant"
      description: |
        Return the information of a tennan
      parameters:
        - in: path
          name: id
          description: ID of the Tenant
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTenantResponse'
      tags:
        - Tenant
      security:
        - api_key: [ 'tenant-read' ]

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    Logo:
      type: object
      properties:
        type:
          description: See https://www.ebaqdesign.com/blog/types-of-logos
          type: string
          enum:
            - EMBLEM
            - PICTORIAL
            - WORDMARK
            - LETTERMARK
            - ABSTRACT
        url:
          type: string
          description: URL of the logo

    PhonePrefix:
      type: object
      properties:
        country:
          type: string
          description: Country code
        prefixes:
          type: array
          items:
            type: string
          description: |
            List of phone prefixed in the format `+<country-code><prefix>`. Ex: `+23799` or `+237950`

    MobileCarrier:
      type: object
      properties:
        code:
          type: string
          description: Mobile carrier unique code
        name:
          type: string
          description: carrier display name
        countries:
          type: array
          description: List of countries covered by this carrier.
          items:
            type: string
        logos:
          description: List of logos of the carrier
          type: array
          items:
            $ref: "#/components/schemas/Logo"
        phonePrefixes:
          description: List of phone prefixes by country
          type: array
          items:
            $ref: "#/components/schemas/PhonePrefix"


    Tenant:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique ID of the tenant
        name:
          type: string
          description: Name of the tenant
        domainName:
          type: string
          description: Tenant domain name
        currency:
          type: string
          description: Currency of this tenant
        numberFormat:
          type: string
          description: Number format
        countries:
          type: array
          description: List of countries supported by this tenant.
          items:
            type: string
        languages:
          type: array
          description: List of languages supported by this tenant.
          items:
            type: string
        logos:
          description: List of logos of the tenant
          type: array
          items:
            $ref: "#/components/schemas/Logo"
        mobileCarriers:
          description: List of phone carriers of the tenant
          type: array
          items:
            $ref: "#/components/schemas/MobileCarrier"

    GetTenantResponse:
      type: object
      properties:
        tenant:
          type: object
          $ref: "#/components/schemas/Tenant"

